
thymeleaf:
  prefix: classpath:/templates/    #指定资源位置
  mode: LEGACYHTML5

server:
  ##  context-path: /webapp
  port: 8674
spring:
  application:
    name: auth-sevice
  security:

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
security:
  loginPage: app/login
  formRest: app/a
  antMatchers: app/*

