
thymeleaf:
  prefix: classpath:/templates/    #指定资源位置
  mode: LEGACYHTML5


security:
  #登录页面
  loginPage: /app/login
  #登录信息提交处理器
  formRest: /app/login.submit
  #拦截过滤路径
  antMatchers:
    - /app/login
    - /app/h1
    - /login
    - /swagger-ui.html
  resources:
    - /css/**
    - /ico/**
    - /js/**
  failureUrl: /app/login?error=true
  defaultSuccessUrl: /app/h1
ribbon:
  #请求处理的超时时间
  ReadTimeout: 30000
  #请求连接的超时时间
  ConnectTimeout: 30000
  #请求缓存刷新时间
  ServerListRefreshInterval: 5000
feign:
  hystrix:
    enabled: false
