
thymeleaf:
  prefix: classpath:/templates/    #指定资源位置
  mode: LEGACYHTML5

  #上传文件大小
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


server:
  ##  context-path: /webapp
  port: 8673
spring:
  application:
    name: kdwl
  cloud:
    config:

      profile: dev
      label: db-config
      name: ${config.name:redis,jdbc,mqs,file,common,email,log}
      discovery:
        enabled: true
        service-id: zfs-config
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/