spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  messages:
    encoding: UTF-8
    basename: i18n/messages

  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: web

  sleuth:
    sampler:
      percentage: 1.0

ribbon:
  #请求处理的超时时间
  ReadTimeout: 30000
  #请求连接的超时时间
  ConnectTimeout: 30000
  #请求缓存刷新时间
  ServerListRefreshInterval: 5000

management:
  security:
    enabled: false