fdfs:
  # 读取时间
  soTimeout: 1501
  # 连接超时时间
  connectTimeout: 691
  # 编码默认UTF-8，charset属性不能自定义
  # charset: UTF-8
  # 缩略图
  thumbImage:
    # 宽
    width: 150
    # 高
    height: 150
  # tracker列表
  trackerList:
  - 47.93.16.119:22122
