logging:
  path: /usr/yunwang/log

  pattern:
    #        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} [%thread] %-5level %class - %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    #   <property name="CONSOLE_LOG_PATTERN" value="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>
    #   <property name="FILE_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"/>

  level:
    ROOT: INFO
    org.apache: ERROR
    org.apache.http: DEBUG
    org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader: ERROR
    org.springframework.web: ERROR
    org.springframework.security.web.util.matcher: ERROR
    org.springframework.bean: ERROR
    org.springframework.context: ERROR
    org.xnio: ERROR
    springfox: ERROR
    io.undertow: ERROR
    org.hibernate: ERROR
    org.dozer: ERROR
    jdbc.connection: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: INFO
    jdbc.audit: OFF
    jdbc.sqltiming: OFF
    jdbc.sqlonly: INFO
    com.minlia.mit: DEBUG
    com.minlia.cloud: OFF
    com.zaxxer.hikari: OFF
    javax.management: OFF
    com.minlia: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.support: DEBUG
    org.springframework.context.annotation: ERROR
    org.springframework.cache.interceptor: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG
    com.hazelcast: INFO
    org.aopalliance.intercept: DEBUG
    org.apache.http.impl.conn: ERROR
    org.apache.http.wire: ERROR
